version: '3.8'
services:
  vault:
    image: hashicorp/vault
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=test
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault_tls/logs:/vault/logs/:rw
      - ./vault_tls/data:/vault/data/:rw
      - ./vault_tls/config:/vault/config/:rw
      - ./vault_tls/certs:/certs/:rw
      - ./vault_tls/file:/vault/file/:rw
    command: server -dev

volumes:
  vault_data: