version: '3'
services:
  database:
    image: postgres:17
    container_name: postgresql
    ports:
    - 5432:5432
    networks:
      cluster_psql:
    restart: always
    environment:
      POSTGRES_USER: vault
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: vault
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  vault_1:
    image: hashicorp/vault
    container_name: vault_1
    ports:
    - 8201:8200
    networks:
      cluster_psql:
        ipv4_address: 192.168.100.5
    environment:
      - VAULT_ADDR=http://192.168.100.5:8200
      - VAULT_ADDRESS=http://192.168.100.5:8200
      - VAULT_API_ADDR=http://192.168.100.5:8200
      - VAULT_SKIP_VERIFY=True
    volumes:
      - ./vault_1.hcl:/vault/config/vault.hcl:ro
    entrypoint: >
      vault server -config=/vault/config/vault.hcl
    cap_add:
      - IPC_LOCK 
    depends_on:
    - database

  vault_2:
    image: hashicorp/vault
    container_name: vault_2
    ports:
    - 8202:8200
    networks:
      cluster_psql:
        ipv4_address: 192.168.100.3
    environment:
      - VAULT_ADDR=http://192.168.100.3:8200
      - VAULT_ADDRESS=http://192.168.100.3:8200
      - VAULT_API_ADDR=http://192.168.100.3:8200
      - VAULT_SKIP_VERIFY=True
    volumes:
      - ./vault_2.hcl:/vault/config/vault.hcl:ro 
    entrypoint: >
      vault server -config=/vault/config/vault.hcl
    cap_add:
      - IPC_LOCK 
    depends_on:
    - database

  vault_3:
    image: hashicorp/vault
    container_name: vault_3
    ports:
    - 8203:8200
    networks:
      cluster_psql:
        ipv4_address: 192.168.100.4
    environment:
      - VAULT_ADDR=http://192.168.100.4:8200
      - VAULT_ADDRESS=http://192.168.100.4:8200
      - VAULT_API_ADDR=http://192.168.100.4:8200
      - VAULT_SKIP_VERIFY=True
    volumes:
      - ./vault_3.hcl:/vault/config/vault.hcl:ro 
    entrypoint: >
      vault server -config=/vault/config/vault.hcl
    cap_add:
      - IPC_LOCK 
    depends_on:
    - database

volumes:
  postgres_data:

networks:
  cluster_psql:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1
