version: '3.3'
services:
  vault:
    image: hashicorp/vault
    container_name: vault-tls
    environment:
      VAULT_ADDR: "https://127.0.0.1:9200"
      VAULT_API_ADDR: "https://127.0.0.1:9200"
      VAULT_ADDRESS: "https://127.0.0.1:9200"
    ports:
      - "9200:9200"
      - "9201:9201"
    volumes:
      - ./logs:/vault/logs/:rw
      - ./data:/vault/data/:rw
      - ./config:/vault/config/:rw
      - ./certs:/certs/:rw
      - ./file:/vault/file/:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config /vault/config/config.hcl -dev